import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopMenu from "@/components/topMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopMenu />
        <div className="pt-[80px] bg-[#0f2e5a]">{children}</div>
      </body>
    </html>
  );
}
