"use client";import React from "react";import { Grid, Box, Typography, Paper, Divider, Chip } from "@mui/material";
// Custom Display Fieldconst DisplayField = ({ label, value }) => (  <Box    sx={{      mt: 2,      mb: 2,      p: 2,      border: "1px solid #e0e0e0",      borderRadius: 1,      boxShadow: "0 1px 3px rgba(0,0,0,0.05)",      backgroundColor: "#fafafa",    }}  >    <Typography      variant="subtitle1"      sx={{ mb: 0.5, fontWeight: "medium", color: "text.secondary" }}    >      {label}    </Typography>    <Typography      variant="body1"      sx={{        pl: 1,        fontWeight: 500,        fontSize: "1.05rem",        color: "#1a237e",      }}    >      {value || "No especificado"}    </Typography>  </Box>);
// Name Display Componentconst NameDisplay = ({ title, apellidoPaterno, apellidoMaterno, nombres }) => (  <Box    sx={{      p: 2,      border: "1px solid #e0e0e0",      borderRadius: 1,      boxShadow: "0 1px 3px rgba(0,0,0,0.05)",      backgroundColor: "#fafafa",    }}  >    <Typography      variant="subtitle1"      sx={{ mb: 1, fontWeight: "medium", color: "text.secondary" }}    >      {title}    </Typography>    <Typography      variant="body1"      sx={{        pl: 1,        fontWeight: 500,        fontSize: "1.05rem",        color: "#1a237e",      }}    >      {`${apellidoPaterno || ""} ${apellidoMaterno || ""} ${nombres || ""}`}    </Typography>  </Box>);
const DetailInscription = () => {  // Mock data - this would come from your API in a real implementation  const inscriptionData = {    competitor: {      apellidoPaterno: "Pérez",      apellidoMaterno: "Gómez",      nombres: "Juan Carlos",      email: "juan.perez@example.com",      ci: "12345678",      fechaNacimiento: "15/05/2006",      colegio: "Colegio San Ignacio",      curso: "4to Secundaria",      departamento: "La Paz",      provincia: "Murillo",      area: "Matemática",    },    tutor: {      apellidoPaterno: "Rodríguez",      apellidoMaterno: "López",      nombres: "María Elena",      email: "maria.rodriguez@example.com",      celular: "71234567",      comprobante: "comprobante_12345.pdf",    },    estado: "Aprobado",    fechaInscripcion: "10/03/2025",  };
  const { competitor, tutor, estado, fechaInscripcion } = inscriptionData;
  return (    <div className="min-h-screen max-w-[1400px] mx-auto lg:px-16 bg-primary-600 p-8">      <Box        sx={{          display: "flex",          justifyContent: "space-between",          alignItems: "center",          mb: 4,        }}      >        <Typography variant="h4" color="white">          Detalle de Inscripción        </Typography>        <Chip          label={estado}          color={            estado === "Aprobado"              ? "success"              : estado === "Pendiente"              ? "warning"              : "error"          }          sx={{ fontWeight: "bold", fontSize: "1rem" }}        />      </Box>
      <Typography variant="subtitle1" color="white" sx={{ mb: 2 }}>        Fecha de inscripción: {fechaInscripcion}      </Typography>
      {/* Seccion Competidor */}      <Paper elevation={2} sx={{ p: 3, mb: 4, borderRadius: 2 }}>        <Typography          variant="h5"          align="center"          sx={{ mb: 3, fontWeight: "medium" }}        >          DATOS DEL COMPETIDOR        </Typography>
        <Box sx={{ display: "flex", flexDirection: "column", gap: 3 }}>          <NameDisplay            title="Nombre del Competidor:"            apellidoPaterno={competitor.apellidoPaterno}            apellidoMaterno={competitor.apellidoMaterno}            nombres={competitor.nombres}          />
          <Divider />
          <Grid container spacing={2}>            <Grid item xs={12} md={4}>              <DisplayField                label="Correo Electrónico:"                value={competitor.email}              />            </Grid>            <Grid item xs={12} md={4}>              <DisplayField label="Cédula Identidad:" value={competitor.ci} />            </Grid>            <Grid item xs={12} md={4}>              <DisplayField                label="Fecha de nacimiento:"                value={competitor.fechaNacimiento}              />            </Grid>          </Grid>
          <DisplayField label="Colegio:" value={competitor.colegio} />
          <Grid container spacing={2}>            <Grid item xs={12} md={4}>              <DisplayField label="Curso:" value={competitor.curso} />            </Grid>            <Grid item xs={12} md={4}>              <DisplayField                label="Departamento:"                value={competitor.departamento}              />            </Grid>            <Grid item xs={12} md={4}>              <DisplayField label="Provincia:" value={competitor.provincia} />            </Grid>          </Grid>
          <DisplayField            label="Área a la que se Inscribe:"            value={competitor.area}          />        </Box>      </Paper>
      {/* Seccion Tutor */}      <Paper elevation={2} sx={{ p: 3, mb: 4, borderRadius: 2 }}>        <Typography          variant="h5"          align="center"          sx={{ mb: 3, fontWeight: "medium" }}        >          DATOS DE PROFESOR/TUTOR        </Typography>
        <Box sx={{ display: "flex", flexDirection: "column", gap: 3 }}>          <NameDisplay            title="Nombre del Profesor o Tutor:"            apellidoPaterno={tutor.apellidoPaterno}            apellidoMaterno={tutor.apellidoMaterno}            nombres={tutor.nombres}          />          <Divider />          <DisplayField label="Correo electrónico:" value={tutor.email} />          <DisplayField label="Celular:" value={tutor.celular} />
          <Box sx={{ mt: 2, mb: 2 }}>            <Box              sx={{                p: 2,                border: "1px solid #e0e0e0",                borderRadius: 1,                boxShadow: "0 1px 3px rgba(0,0,0,0.05)",                backgroundColor: "#fafafa",              }}            >              <Typography                variant="subtitle1"                sx={{ mb: 1, fontWeight: "medium", color: "text.secondary" }}              >                Comprobante de pago:              </Typography>              <Box sx={{ pl: 1 }}>                <Chip                  label={tutor.comprobante}                  color="primary"                  variant="outlined"                  component="a"                  href="#"                  clickable                  sx={{ cursor: "pointer" }}                />              </Box>            </Box>          </Box>        </Box>      </Paper>
      <Box        sx={{          display: "flex",          justifyContent: "space-between",          mt: 4,          color: "white",        }}      >        <Chip          label="Volver"          color="default"          variant="outlined"          component="a"          href="/inscriptions"          clickable          sx={{            cursor: "pointer",            px: 4,            py: 3,            fontSize: "1rem",            borderRadius: 1,            backgroundColor: "white",            color: "primary.main",            "&:hover": {              backgroundColor: "grey.100",            },          }}        />        <Chip          label="Imprimir comprobante"          color="primary"          component="a"          href="#"          clickable          sx={{            cursor: "pointer",            px: 4,            py: 3,            fontSize: "1rem",            borderRadius: 1,            backgroundColor: "#e53e3e",            color: "white",            "&:hover": {              backgroundColor: "#c53030",            },          }}        />      </Box>    </div>  );};
export default DetailInscription;